version: "3.8"

services:
  optisigns-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: optisigns-bot
    container_name: optisigns-bot-container
    env_file:
      - .env
    volumes:
      - ./metadata_storage:/app
    command: python main.py
