version: "3.8"

services:
  optisigns-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: optisigns-bot:latest # Name the image
    container_name: optisigns-bot-container # Name the container
    env_file:
      - .env # Load environment variables from .env file
    restart: "no" # Explicitly set no restart policy
    command: python main.py # Command to run when the container starts
